steps:

  #Build 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ninth-history-314409/cloud-run-django:$COMMIT_SHA', '-f', 'python/cloud-run-django-hello-world/Dockerfile', 'python/cloud-run-django-hello-world']
    id: BUILD


  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ninth-history-314409/cloud-run-django:$COMMIT_SHA']
    id: STORAGE

  # Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'cloud-run-django',
      '--image', 'gcr.io/ninth-history-314409/cloud-run-django:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    id: DEPLOY

options:
  logging: CLOUD_LOGGING_ONLY